---
title: "R Notebook"
output: html_notebook
---


```{r}
options(max.print=1000000)
library(readxl)
library(dplyr)
fileName <- "ANZ synthesised transaction dataset.xlsx"
df <- as.data.frame(read_xlsx(fileName))
xl <- df

```

```{r}


### Average Transaction amount ###
avg_transaction <- mean(df$amount)

{
  plot(avg_transaction, ylab="Average Transaction")
  abline(h=avg_transaction, col='blue')
  legend("topright", legend=paste("Mean: ", round(avg_transaction, digits=2)),
       col="blue", lty=1:2, cex=0.8)
  title(expression(phantom("title (") * "Average Transaction Amount"), col.main = "purple")
}
```

```{r}

library(dplyr)
library(ggplot2)
df$date <- as.Date(df$date)
week_var <- strftime(df$date, format = "%V")
week_var <- factor(week_var)
amount_spent_weekly <- aggregate(df$amount, list(week_var), sum)
week_numbers <- c()
week_start <- as.numeric(amount_spent_weekly$Group.1[1])
week_end <- length(amount_spent_weekly$Group.1)
for (i in seq_along(week_start:week_end)){
  week_numbers <- append(week_numbers, i+1 - week_start)
}

{
  png(filename="weekly_amount.png", width=1350, height=600)
  
  ### ggplot init
  
  plt <- ggplot(amount_spent_weekly, aes(week_numbers, x, group=1))
  
  ### Labels
  
  l <- labs(x="Week", y="Amount", title="Amount by week")
  
  ### theme start
  
  t<- theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1, size=12, face="bold", colour = "blue"), 
            plot.title = element_text(size=16, face= "bold", colour= "brown" ),
    axis.title.x = element_text(size=14, face="bold", colour = "orange"),    
    axis.title.y = element_text(size=14, face="bold", colour = "orange"),    
    #axis.text.x = element_text(size=12, face="bold", colour = "black"), 
    axis.text.y = element_text(size=12, face="bold", colour = "blue")) 
  
  ###theme end
  
  print(plt+geom_point(size=6, col="red")+geom_line(color="blue", size=1)+l+t + scale_x_continuous(breaks=seq(1, 14, 1)))
  dev.off()
}
  print(plt+geom_point(size=6, col="red")+geom_line(color="blue", size=1)+l+t + scale_x_continuous(breaks=seq(1, 14, 1)))


```

```{r}
library(lubridate)
library(dplyr)
library(collapsibleTree)

amount_account_data <- c()

df <- arrange(df, factor(df$account))

account_fact <- factor(df$account)
p <- aggregate(df$amount, list(account_fact), sum)
customer_id_fact <- factor(df$customer_id)
amount_account_data <- append(amount_account_data, p)
z <- c()
for (o in levels(customer_id_fact)){
  z <- append(z, o) #z
}
z <- bind_rows(as.data.frame(z))
amount_account_data <- append(amount_account_data, z)


```

```{r}
#library(webshot)
z1 <- c()
namesA <- c()

for (k in seq_along(1:100)){
  namesA <- filter(df, df$account == amount_account_data$Group.1[k]) 
  z1 <- append(z1, namesA$first_name[1])
}
z1 <- bind_rows(as.data.frame(z1))
amount_account_data <- append(amount_account_data, z1)
amount_account_data <- as.data.frame(amount_account_data)

c <- collapsibleTree(
  amount_account_data,
  hierarchy = c("z1", "Group.1", "z", 'x'),
  root = "Customer Details",
  width = 1100,
  height=1400,
  zoomable = FALSE,
  collapsed = TRUE,
)
htmltools::save_html(c, file='CustomerDetailsTree.html')
nrow(df)
# widgetToPng <- function(widget, file = "widget.png",  ...) {
#   temp <- tempfile(fileext = ".html")
#   file <- R.utils::getAbsolutePath(file)
#   htmlwidgets::saveWidget(widget, temp)
#   webshot(
#     temp, file,
#     selector = "#htmlwidget_container",
#     zoom = 2,
#     delay = 0.5,
#     ...
#   )
# }
# widgetToPng(
#   collapsibleTreeSummary(
#   amount_account_data,
#   hierarchy = c("z1", "Group.1", "z", 'x'),
#   width = 1100,
#   height=1400,
#   collapsed = FALSE,
#   maxPercent = 50,
#   root = "Customer Details",
#   zoomable = FALSE
# ),
#   "CustomerDetailsTree.png"
# )


```

```{r}
p1<-data.frame()
p1 <- aggregate(df$amount, list(account_fact), mean)

{
  png(filename="outliers.png", width=1350, height=600)
  
  ### Labels
  
  l1 <- labs(x="Accout ID", y="Average Value", title="Outliers", colour='Outliers', size=14)
  
  ### Theme Start
      
  t1<- theme(legend.position = c(.98, .98), legend.justification = c("right", "top"),axis.text=element_text(size=12), axis.title=element_text(size=14,face="bold"), 
     legend.title=element_text(colour='red', size=19), axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1, size=12))
  
  ### Geom_Point
  gp <- geom_point(col='blue', size=4)
  
  ### Geom_Text
  gt <- geom_text(aes(label= ifelse(p1[, 'x'] > quantile(p1[, 'x'], 0.97) | p1[, 'x'] < quantile(p1[, 'x'], 0.01),
     as.character(p1[, 'Group.1']),'')),hjust=0,vjust=1,size=6,show.legend =T)
  ### Lapply, ggplot
  list_plots <- lapply(p1[-1], function(data) 
     ggplot(p1, aes(x= Group.1, y = x, colour='orange', label=p1[, 'Group.1'])) + t1 + l1 + gp + gt)

  print(list_plots[[1]])
  dev.off()
}


```

```{r}

p2 <-data.frame()
p2<-aggregate(df$amount, list(factor(df$merchant_long_lat)), sum)
{
  png(filename="merchant_long_lat.png", width=1400, height=800)
  
  ### Labels
  
  l2 <- labs(x="Merchants Location", y="Total Amount", title="Amount Information w/ Merchant Lat Long")
  
  ### Theme Start
      
  t2<- theme(axis.text=element_text(size=12), axis.title=element_text(size=20,face="bold"),
     axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1, size=8, face='bold'))
  
  ### Geom_Point
  gp2 <- geom_point(col='blue', size=4)
  
  ### Geom_Text
  gt2 <- geom_text(aes(label=ifelse(p2[, 'x']>=4000, as.character(p2[, 'Group.1']),''), hjust=0,vjust=1,size=10))
  ### Lapply, ggplot
  
  ggplt <- ggplot(p2, aes(x= 1:length(p2$Group.1), y = x)) +  l2 + t2 + gp2 + gt2

  print(ggplt)
  dev.off()
}



```

